### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by MaartenProvo** [DrHauss/node-red-contrib_BRP069C4#4] opened 2021-10-21 08:00 UTC
I've been using this node sucessfully for a couple of months, but since a week or two it started giving this error:
`HTTPError: Response code 400 (Bad Request)`
I thought it had to do something with the firmware update, which I executed today. But that didn't solve it. I haven't changed anything else, it just stopped working. I tried re-entering my settings, setting it up from scratch but it keeps giving me this error.

**Comment by fiendie** [comment] 2021-11-07 15:49
I'm experiencing the same issue. 
Started occurring out of the blue today after using it for a few weeks.

**Comment by bartjanisse** [comment] 2021-11-07 16:33
Me too. Had it before. I deleted the tokenset.json and restarted Node red. After that it seems to rune fine again. 

Somehow I think the token gets out of date. 

Maybe there could be some mechanism to refresh the token every 3 weeks or so (just a thought)

**Comment by fiendie** [comment] 2021-11-07 21:20
@bartjanisse: That did the trick, thanks ;)

**Comment by MaartenProvo** [comment] 2021-11-17 22:15
Great, that did the trick.

**Comment by DrHauss** [comment] 2021-12-20 22:13
I think the problem is that the tokenset.json is broken at some point. I had the same issue some time ago but have not logs to get into this topic more deeper. I implemented a setting in the Daikin Cloud device to not save the "tokenset.json".  This could be done by setting the "Save token" value to Disabled in your node.

**Comment by DrHauss** [comment] 2021-12-20 22:27
@bartjanisse @MaartenProvo  @fiendie 

Also check this pull request on the daikin-cloud-controller lib which is used here by this node.

[Timeout and retry for GOT client](https://github.com/Apollon77/daikin-controller-cloud/pull/19)

After adding the timeout and retry functionality it is now safer for me to update the token. 

Since this functionality is not released into the latest version of Daikin-cloud-controller lib please use the version from  GitHub. The actual released version which is automatically installed with this npm does not support the settings for retry and timeout and ignore whatever you set in the node config. When there is a timeout during update of tokenset.json this might broke your tokenset.json.

**Closed by DrHauss** 2021-12-20 22:27 UTC
Labels: bug
